# Generated by Django 3.1.3 on 2021-01-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='my_pics'),
        ),
    ]
