# Generated by Django 3.1.3 on 2021-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_me_background_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name': 'Me', 'verbose_name_plural': 'Me'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_3',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_4',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
    ]
