# Generated by Django 3.1.3 on 2021-01-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210124_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
